In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data_nlp/enriched_copyright_cases.csv")
df.head()

,case_name_final,case_name,year_final,court_final,judge_final,docket_number_final,docket_number_clean,citation_clean,recap_found,recap_query_used,...,substantial_similarity_flag_final,substantial_similarity_count_final,injunction_flag_final,injunction_count_final,damages_flag_final,damages_count_final,fair_use_factor1_purpose_final_count,fair_use_factor2_nature_final_count,fair_use_factor3_amount_final_count,fair_use_factor4_market_final_count
0,GPNE Corp. v. Apple Inc.,"Andersen v. Stability AI Ltd., 2025 U.S. Dist....",2012,"District Court, N.D. California",Lucy Haeran Koh,5:12-cv-02885,5:12-cv-2885-LHK,2025 U.S. Dist. LEXIS 133840,True,"""5:12-cv-2885-LHK""",...,False,0,False,0,False,0,0,0,0,0
1,Williamson v. Haywood County Justice Complex,"In re Openai, Inc., 2026 U.S. Dist. LEXIS 76901",2014,"District Court, W.D. Tennessee",James Dale Todd,1:14-cv-01254,14-CV-1254,2026 U.S. Dist. LEXIS 76901,True,"docketNumber:""14-CV-1254""",...,False,0,False,0,False,0,8,0,0,0
2,"Halcyon Horizons, Incorporated v. Delphi Behav...","Hollis v. Render, 2025 U.S. Dist. LEXIS 139005",2017,"District Court, N.D. California",Jon Steven Tigar,4:17-cv-00756,17-cv-00756-JST,2025 U.S. Dist. LEXIS 139005,True,"""17-cv-00756-JST""",...,False,0,False,0,False,0,10,4,0,0
3,"Synopsys, Inc. v. Real Intent, Inc.","Synopsys, Inc. v. Real Intent, Inc., 2024 U.S....",2020,"District Court, N.D. California",Edward John Davila,5:20-cv-02819,20-cv-02819-EJD,2024 U.S. Dist. LEXIS 239030,True,"""20-cv-02819-EJD""",...,False,0,False,0,True,16,8,0,0,2
4,"Apple Inc. v. Rivos, Inc.","Flexport, Inc. v. Freightmate AI, Inc., 2025 U...",2022,"District Court, N.D. California",P. Casey Pitts,5:22-cv-02637,5:22-cv-02637-EJD,2025 U.S. Dist. LEXIS 161200,True,"""5:22-cv-02637-EJD""",...,False,0,False,0,False,0,0,0,0,0

In [3]:
df1 = pd.read_csv("data_nlp/final_ai_copyright_nlp_output.csv")
df1.head()

,case_name_final,case_name,year_final,court_final,judge_final,docket_number_final,docket_number_clean,citation_clean,recap_found,recap_query_used,...,remedy_pressure_index,case_theme,dominant_topic,dominant_topic_score,topic_keywords,top_tfidf_keywords,text_cluster,cluster_keywords,nearest_case_name,nearest_case_similarity
0,GPNE Corp. v. Apple Inc.,"Andersen v. Stability AI Ltd., 2025 U.S. Dist....",2012,"District Court, N.D. California",Lucy Haeran Koh,5:12-cv-02885,5:12-cv-2885-LHK,2025 U.S. Dist. LEXIS 133840,True,"""5:12-cv-2885-LHK""",...,0.000000,training_data_copyright,3,0.377147,"mr, dr, amazon, royalty, patent, zhao, expert",zhao; dr; highly confidential; defendants; con...,1,"defendants, openai, complaint, plaintiffs, 3d,...","Apple Inc. v. Rivos, Inc.",0.385093
1,Williamson v. Haywood County Justice Complex,"In re Openai, Inc., 2026 U.S. Dist. LEXIS 76901",2014,"District Court, W.D. Tennessee",James Dale Todd,1:14-cv-01254,14-CV-1254,2026 U.S. Dist. LEXIS 76901,True,"docketNumber:""14-CV-1254""",...,0.000000,training_data_copyright,1,0.447740,"llp, ca, plaintiffs, francisco ca, san, san fr...",mr; deposition; project; llp; deponent; rule 3...,3,"llp, plaintiffs, ca, francisco ca, san francis...","In Re: OpenAI, Inc. Copyright Infringement Lit...",0.605670
2,"Halcyon Horizons, Incorporated v. Delphi Behav...","Hollis v. Render, 2025 U.S. Dist. LEXIS 139005",2017,"District Court, N.D. California",Jon Steven Tigar,4:17-cv-00756,17-cv-00756-JST,2025 U.S. Dist. LEXIS 139005,True,"""17-cv-00756-JST""",...,0.000000,training_data_copyright,0,0.228720,"openai, complaint, plaintiffs, defendants, 3d,...",laches; trademark; statute limitations; 3d; li...,2,"mark, ravine, trademark, ai, decl, marks, fac","Playground AI LLC v. Mighty Computing, Inc.",0.274173
3,"Synopsys, Inc. v. Real Intent, Inc.","Synopsys, Inc. v. Real Intent, Inc., 2024 U.S....",2020,"District Court, N.D. California",Edward John Davila,5:20-cv-02819,20-cv-02819-EJD,2024 U.S. Dist. LEXIS 239030,True,"""20-cv-02819-EJD""",...,0.296296,training_data_copyright,3,0.576177,"mr, dr, amazon, royalty, patent, zhao, expert",dr; real; intent; opinions; mr; fair use; rep;...,4,"mr, flycatcher, amazon, royalty, feldman, dr, ...","Dialect, LLC v. Amazon.Com, Inc.",0.327801
4,"Apple Inc. v. Rivos, Inc.","Flexport, Inc. v. Freightmate AI, Inc., 2025 U...",2022,"District Court, N.D. California",P. Casey Pitts,5:22-cv-02637,5:22-cv-02637-EJD,2025 U.S. Dist. LEXIS 161200,True,"""5:22-cv-02637-EJD""",...,0.000000,training_data_copyright,0,0.128071,"openai, complaint, plaintiffs, defendants, 3d,...",zhao; trade; secrets; trade secrets; trade sec...,1,"defendants, openai, complaint, plaintiffs, 3d,...",GPNE Corp. v. Apple Inc.,0.385093

In [4]:
df2 = pd.read_csv("data_nlp/ai_copyright_case_summary_for_paper.csv")
df2.head()

,case_name_final,year_final,court_final,judge_final,docket_number_final,recap_found,opinion_found,data_source_for_text,true_ai_defendants_final,plaintiff_type_lexis,...,training_data_nlp_score,scraping_nlp_score,market_harm_nlp_score,memorization_output_nlp_score,dmca_cmi_nlp_score,training_data_conflict_index,fair_use_salience_index,output_risk_index,remedy_pressure_index,case_summary_final
0,GPNE Corp. v. Apple Inc.,2012,"District Court, N.D. California",Lucy Haeran Koh,5:12-cv-02885,True,True,LexisNexis Text + RECAP Metadata,Stability AI,visual_artist_or_image_owner,...,9,0,0,6,0,0.078261,0.000000,0.050847,0.000000,"Andersen v. Stability AI Ltd., 2025 U.S. Dist...."
1,Williamson v. Haywood County Justice Complex,2014,"District Court, W.D. Tennessee",James Dale Todd,1:14-cv-01254,True,True,LexisNexis Text + RECAP Metadata,OpenAI,news_publisher,...,3,0,0,6,0,0.026087,0.228571,0.050847,0.000000,"In re Openai, Inc., 2026 U.S. Dist. LEXIS 7690..."
2,"Halcyon Horizons, Incorporated v. Delphi Behav...",2017,"District Court, N.D. California",Jon Steven Tigar,4:17-cv-00756,True,True,LexisNexis Text + RECAP Metadata,NaN,book_author_or_author_group,...,1,0,0,0,0,0.008696,0.285714,0.000000,0.000000,"Hollis v. Render, 2025 U.S. Dist. LEXIS 139005..."
3,"Synopsys, Inc. v. Real Intent, Inc.",2020,"District Court, N.D. California",Edward John Davila,5:20-cv-02819,True,True,LexisNexis Text + RECAP Metadata,NaN,book_author_or_author_group,...,1,0,10,0,0,0.564251,1.221992,0.000000,0.296296,"Synopsys, Inc. v. Real Intent, Inc., 2024 U.S...."
4,"Apple Inc. v. Rivos, Inc.",2022,"District Court, N.D. California",P. Casey Pitts,5:22-cv-02637,True,False,LexisNexis Text + RECAP Metadata,NaN,book_author_or_author_group,...,5,0,0,0,2,0.043478,0.000000,0.000000,0.000000,"Flexport, Inc. v. Freightmate AI, Inc., 2025 U..."